app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager

class User(db.Model,UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    pass_secure  = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


    def __repr__(self):
        return f'User {self.username}'



class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'

class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    pitches = db.relationship('Pitch', backref='category', lazy='dynamic')
    # comments = db.relationship('Comment', backref='user', lazy='dynamic')

    def save_category(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_categories(cls):
        categories = Category.query.all()
        return categories

class Pitch(db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer, primary_key=True)
    pitch = db.Column(db.String(255))
    
    category_id = db.Column(db.Integer, db.ForeignKey("categories.id"))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comment', backref='pitch', lazy='dynamic')

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls, category_id):
        pitches = Pitch.query.order_by(Pitch.id.desc()).filter_by(category_id=category_id).all()

        return pitches


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    pitch_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))
    #user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, pitch_id):
        comments = Comment.query.order_by(Comment.id.desc()).filter_by(pitch_id=pitch_id).all()

        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required


class CategoryForm(FlaskForm):
    """
    class to create a form to create category
    """
    name = StringField('Pitch Category',validators=[Required()])
    submit = SubmitField('Create')


class PitchForm(FlaskForm):
    """
    class to create form to write pitch
    """
    pitch = StringField('Pitch Content', validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    """
    class to create form to comment on a pitch
    """
    comment = StringField('Comment Content', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'



bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):

  # Initializing application
  app = Flask(__name__)

  # Creating the app configurations
  app.config.from_object(config_options[config_name])

  # Initializing flask extensions
  bootstrap.init_app(app)
  db.init_app(app)
  login_manager.init_app(app)


  

  # Registering the main blueprint
  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)

  # Registering the auth blueprint
  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint)


 
  return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,redirect,url_for
from .import main
from flask_login import login_required,current_user
from .forms import CategoryForm,PitchForm,CommentForm
from ..models import Category,Pitch,Comment

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    category=Category.get_categories()


    title = "Welcome | One Minute Pitch"
    return render_template('index.html',title=title, category=category)


@main.route('/category/new', methods=['GET', 'POST'])
@login_required
def profile_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        profile_category = Category(name=name)
        profile_category.save_category()
        return redirect(url_for('main.index'))
    title = 'New Pitch Category'
    return render_template('profile_category.html', category_form=form)


@main.route('/category/<int:id>')
def category(id):
    category = Category.query.get(id)
    pitch = Pitch.query.filter_by(category_id=id)

    title = f'{category.name} page'

    return render_template('category.html',title=title, category=category,pitch=pitch)

@main.route('/category/pitch/new/<int:id>', methods=['GET', 'POST'])
@login_required
def new_pitch(id):
    category = Category.query.get(id)
    form = PitchForm()
    if form.validate_on_submit():
        pitch = form.pitch.data
        new_pitch = Pitch(pitch=pitch, category_id=id)
        new_pitch.save_pitch()
        return redirect(url_for('.category', id=id))

    title = 'New Pitch'
    return render_template('new_pitch.html', title=title, pitch_form=form, category=category)


@main.route('/pitch/<int:id>')
def pitch(id):
    pitch = Pitch.query.get(id)
    comment = Comment.get_comments(pitch_id=id)

    # Comment.query.order_by(Comment.id.desc()).filter_by(pitch_id=id).all()

    title = f'Pitch { pitch.id }'
    return render_template('pitch.html',title=title, pitch=pitch, comment=comment)


@main.route('/comment/new/<int:id>', methods=['GET', 'POST'])
@login_required
def new_comment(id):
    pitch = Pitch.query.get(id)
    # comment = Comment.query.get(pitch_id)

    form = CommentForm()
    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comment(comment=comment, pitch_id=id)
        new_comment.save_comment()
        return redirect(url_for('.pitch', id=id))
    # title = f' Comment{comment.id}'
    return render_template('new_coment.html', comment_form=form, pitch=pitch)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block styles %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/solar/bootstrap.min.css">
{% endblock %}

{% include 'navbar.html' %}

{% block content %}{% endblock %}

app/templates/category.html
{% extends 'base.html' %} {% block content %}

<div class="container">
    <br>
    <br>
    <br>
    <div class="row">
        <div class="col-md-4">
            <h1>List of {{ category.name }}</h1>
        </div>

        <div class="col-md-8">
            <button type="button" class="btn btn-outline-primary"><a href="/category/pitch/new/{{ category.id }}"> Add Pitch</a></button>

        </div>
    </div>

    {% for pitch in pitch %}
    <div class="card">
        <div class="card-body">
            <a href="/pitch/{{ pitch.id }}">
                <h3>{{ pitch.pitch}}</h3>

            </a>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}

<title> {{ title }} </title>

<div class="container">

  <h1>The url you tried to access doesn't exist</h1>
  <h4>
    This is probably caused by:
    <ul>
      {% for blooper in bloopers %}
      <li>
        <h4>{{blooper}}</h4>
      </li>
      {% endfor %}
    </ul>
  </h4>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %} 
{% block content %}


<title> {{ title }} </title>

<div class="container">
    <br>
    <br>
    <br>
    <h1>HOME PAGE</h1>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4 col-lg-4">
            <h5 class="category-header">LIST OF CATEGORIES:</h5>
        </div>
        <div class="col-md-4 col-lg-4">
        </div>

        <div class="col-md-4 col-lg-4">
            <h2 class="category-create">
                <button type="button" class="btn btn-outline-primary"><a href="/category/new">Add Category</a></button>


            </h2>
        </div>
    </div>

    <div>
        {% for categories in category %}
        <ul>
            <li>
                <a href="/category/{{ categories.id }}"><button type="button" class="btn btn-primary btn-lg btn-block">{{ categories.name }}</button></a>
            </li>
        </ul>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">One Minute Pitch</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      {% if not current_user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.profile_category')}}">My Account</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

app/templates/new_category.html
{% extends 'base.html' %} 
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}

<div class="container">
    <br>
    <br>
    <br>
    <title>{{ title }}</title>
    <div class="row">
        {{ wtf.quick_form(category_form) }}
    </div>
</div>
{% endblock %}

app/templates/new_coment.html
{% extends 'base.html' %} 
{% import 'bootstrap/wtf.html' as wtf%} 


{% block content %}
<div class=container>
    <div class="row">
        <br>
        <br>
        <br>
        <br>
        <title>{{ title }}</title>
        <div class="row">
            {{ wtf.quick_form(comment_form) }}
        </div>

    </div>
</div>
{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html' %} 
{% import 'bootstrap/wtf.html' as wtf%} 


{% block content %}
<div class=container>
    <div class="row">
        <br>
        <br>
        <br>
        <br>
        <title>{{ title }}</title>
        <div class="row">
            {{ wtf.quick_form(pitch_form) }}
        </div>

    </div>
</div>
{% endblock %}

app/templates/pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%} 
{% block content %}

<div class=container>
    <br>
    <br>
    <br>
    <br>
    <div class="row">
        <h1>List Comments</h1>
        <hr>

    </div>
   

    <div class="card">
            <div class="card-body">
              <h3 class="card-title">{{ pitch.pitch}}</h3>
              <p class="card-text">{% for comment in comment %} {{ comment.comment }} <br>{% endfor %}</p>
              <a href="/comment/new/{{ pitch.id }}"><button type="button" class="btn btn-primary">comment</button>
                </a>
            </div>
    </div>


</div>


{% endblock %}

app/templates/profile_category.html
{% extends 'base.html' %} 
{% import 'bootstrap/wtf.html' as wtf%} 
{% block content %}

<div class="container">
    <br>
    <br>
    <br>
    <br>
    <br>
    <title>{{ title }}</title>
    <div class="row">
        {{ wtf.quick_form(category_form) }}
    </div>
</div>
{% endblock %}